config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'notifications/notify'
  post 'events/set_notifs_seen'

  devise_for :users
  resources :events do
   post 'attend', on: :member
  end

  resources :groups do
    post 'subscribe', on: :member
  end

  get 'peoples' => 'peoples#index'

end

app/models/group.rb
class Group
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Sadstory
  include Mongoid::Paperclip

  field :name, type: String
  field :description, type: String

  has_many :events
  has_and_belongs_to_many :subscribers, class_name: "User", inverse_of: :subscribed_groups
  belongs_to :user

  has_mongoid_attached_file :image_attachment
  validates_attachment_file_name :image_attachment, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]

 validates :name,:description,presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    request_type = (params[:request_type].blank? || params[:request_type].length == 0) ? "AllGroups" : params[:request_type]

    if request_type == 'AllGroups'
      @group = Group.all

   elsif request_type == 'Subscribed'
      @group = current_user.subscribed_groups

    elsif request_type == 'MyCreated'
      @group = current_user.groups

    end
  end

  def new
     @group = Group.new
  end

  def edit
     @group = Group.find(params[:id])
   end

   def show
     @group = Group.find(params[:id])	
   end

  def create
     @group = Group.new(params[:group].permit(:name,:description,:image_attachment))     
     @group.user_id = current_user.id
     if @group.save
     redirect_to @group
     else
       render 'new' 
     end
   end

  def update
    @group = Group.find(params[:id])
    if @group.update((params[:group].permit(:name,:description)))
     redirect_to @group
    else
     render 'edit'
    end
  end

  # Add or remove subscription of user for a group
  # User can subscribe to any group.
  def subscribe
    group = Group.find(params[:id])

    if params[:perform] == 'Join'
      current_user.subscribed_groups << group
      group.subscribers << current_user

    elsif params[:perform] == 'Remove'
      current_user.subscribed_group_ids.delete(group.id)
      group.subscriber_ids.delete(current_user.id)
    end

    current_user.save!
    group.save!

    redirect_to groups_path(request_type: params[:request_type])
  end

    def destroy
    @group = Group.find(params[:id])
    @group.destroy
 
    redirect_to groups_path
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="row navbar-clearance">
  <%= form_for @group do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@group.errors.count, "error") %> prohibited
	        this article from being saved:
     	 </h2>
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="panel panel-default webform">
      <div class="panel-heading">
        <h4><%= "Create Group" %></h4>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image_attachment %><br />
          <%= f.file_field :image_attachment, class: "form-control" %>
        </div>
        <%= f.submit :default => "Submit", class: "btn btn-primary btn-sm" %>
        <%= link_to 'Back',groups_path, class: "btn btn-primary btn-sm" %>
      </div> <!-- panel-body -->
    </div> <!-- panel -->
  <% end %>
</div>

app/views/groups/edit.html.erb
<%= render 'form' %>

app/views/groups/index.html.erb
<div class="row navbar-clearance">
  <div class="col-xs-9">
    <div class="btn-group" role="group" aria-label="FilterButtons">
      <%= link_to 'All Groups',groups_path(:request_type => 'AllGroups'), class: "btn btn-default btn-sm filterbtn", id: 'AllGroups' %>
      <%= link_to 'Subscribed',groups_path(:request_type => 'Subscribed'), class: "btn btn-default btn-sm filterbtn", id: 'Subscribed' %>
      <%= link_to 'My Created',groups_path(:request_type => 'MyCreated'), class: "btn btn-default btn-sm filterbtn", id: 'MyCreated' %>
    </div>
  </div>
</div>
<hr/>

<div class="row">
  <div class="col-xs-9">
    <%= link_to 'Create Group',new_group_path, class: "btn btn-default btn-sm" %>
  </div>
</div>
<br/>

<div class="row">
  <div class="col-xs-12">
    <div id="home" class="tab-pane fade in active">
      <% @group.each do |g| %>
      <div class="group-div">
        <div class="thumbnail">
          <a href='<%= group_path(g) %>'>
           <% if !g.image_attachment.blank? %>
                <img  data-holder-rendered="true" style="width: 150px; height: 150px;" src=<%= g.image_attachment.url%> >
            <% else %>
                <img  data-holder-rendered="true" style="width: 150px; height: 150px;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAPFBMVEXw8PDNeJjy9vTMdZbVlq3TkanLcJLn1tzp2t/Mc5TKbZHTj6jSi6Xq3+Pu6+zaqLrJZozhwcz0+/nQg59YUvSoAAABtklEQVR4nO3da04CQRCFUQVmmBnA5/736gZMLJNbnTaes4Cb/oj+I8XTEwAAAPCvPbbBXgYHnpZjHertOrrwcn4ealWoUKFChQoVKlSoUKFChQoVKlSoUKFChQoVKlSoUKFChQq/fX3Bx2U/D3VslWedSoGP5VLwuYx1v1Ve9VpK3I7CR7ovH6XPNOZRetWtVrgW/i3OS+0PIib5KoUKeyhU2LWVo1Bh11aOQoVdWzkKFXZt5ShU2LWVo1Bh11aOQoVdWzkKFXZt5ShU2LWVo1Bh11aOwl8VvhVOHBz30YXBV71cK7bupD/xKgAAAAAAAABoN/aUQFYpsHY1Yk7BqxFzSl6NmFPyO1FzUqhwfgoVzk+hwvkpVDg/hQrnp1Dh/BQqnJ9ChfNTqHB+ChXOT6HC+SWvRqy1nyjZx04lr0Zst8q79vexU8mrEbXfmVmvhc80OJVUfdbYqSSFCnumkhQq7JlKUqiwZypJocKeqSSFCnumkhQq7JlKUqiwZypJocKeqSSFCnumkhQq7JlKUqiwZyrpdNkLFwCOWmFsKun0elt+dq98cyA4FRU8xBGcAgAAgH/rCzxkcZYpG8C9AAAAAElFTkSuQmCC">
       <%end%>
       </a>

          <div class="caption" style="height:55px;overflow:auto;">
            <div style="font-weight:bold;text-align:center;font-size: 15px;word-wrap:break-word;">
              <%= link_to(truncate(g.name || "", length: 60, omission: '...'), group_path(g)) %>
            </div>
          </div> <!--caption-->

          <div style="text-align:center;">
            <span class="glyphicon glyphicon-user"></span>
            <span style="font-family: Helvetica Neue, Helvetica, Arial, sans-serif;"><%= pluralize(g.subscribers.count, '') %></span>
          </div>

          <div style="text-align:center;padding: 10px 0 10px 0;">
            <% if g.subscriber_ids.include? current_user.id %>
              <%= link_to '', subscribe_group_path(g, request_type: params[:request_type], perform: 'Remove'), method: :post,class: "btn btn-default btn-sm glyphicon glyphicon-ok added-to-cal", title: "Click to unsubscribe from this group."  %>
            <% else %>
              <%= link_to '', subscribe_group_path(g, request_type: params[:request_type], perform: 'Join'), method: :post,class: "btn btn-default btn-sm glyphicon glyphicon-plus", title: "Click to subscribe to this group."  %>
            <% end %>
            <% if g.user_id == current_user.id %> <!-- current user is the group admin -->
               <%= link_to '',edit_group_path(g),class: "btn btn-default btn-sm glyphicon glyphicon-pencil", title: "Edit" %>
               <%= link_to '',group_path(g),method: :delete, data: {confirm: 'Are you sure?'},class: "btn btn-default btn-sm glyphicon glyphicon-trash", title: "Delete" %>
               <%= link_to 'Add Events', new_event_path({group_id: g.id}), class: "btn btn-default btn-sm", title: "Add new events to this group." %>
            <% end %>
          </div>
        </div> <!--thumbnail-->
      </div> <!--col-xs-3-->
    <% end %>

    </div>
  </div>
</div>

<script>
  var request_type = '<%= params[:request_type] %>';

  // Select active tab
  if(request_type.length > 0) {
    $('.filterbtn').removeClass('active')
    $('#'+request_type).addClass('active')
  } else {
    $('#AllGroups').addClass('active')
  }

</script>

app/views/groups/new.html.erb
<%= render 'form' %>

app/views/groups/show.html.erb
<div class="row navbar-clearance">
  <div class="panel panel-default webform">
    <div class="panel-heading">
      <h4><%= "Group Details" %></h4>
    </div> 
    <div class="panel-body">
      <div class="form-group">
        <h6><b><%= "Name:" %></b></h6>
        <%= @group.name %>
      </div>
      <div class="form-group">
        <h6><b><%= "Description:" %></b></h6>
        <%= @group.description %>
      </div>
      <div class="form-group">
        <h6><b><%= "Group Image:" %></b></h6>
        <%= image_tag @group.image_attachment %>
      </div>
    </div> <!--panel-body-->
  </div> <!--panel-->
</div> <!--row-->

<br/>
<div class="row">
  <div class="col-xs-9">
  <% if @group.subscriber_ids.include? current_user.id %>
    <%= link_to '', subscribe_group_path(@group, request_type: params[:request_type], perform: 'Remove', current_cal: params[:current_cal]), method: :post,class: "btn btn-default btn-sm glyphicon glyphicon-ok added-to-cal", title: "Click to unsubscribe from this group."  %>
  <% else %>
    <%= link_to '', subscribe_group_path(@group, request_type: params[:request_type], perform: 'Join', current_cal: params[:current_cal]), method: :post,class: "btn btn-default btn-sm glyphicon glyphicon-plus", title: "Click to subscribe to this group."  %>
  <% end %>
  <% if @group.user_id == current_user.id %> <!-- current user is the group admin -->
    <%= link_to '',edit_group_path(@group),class: "btn btn-default btn-sm glyphicon glyphicon-pencil", title: "Edit" %>
    <%= link_to '',group_path(@group),method: :delete, data: {confirm: 'Are you sure?'},class: "btn btn-default btn-sm glyphicon glyphicon-trash", title: "Delete" %>
    <%= link_to 'Add Events', new_event_path({group_id: @group.id}), class: "btn btn-default btn-sm", title: "Add new events to this group." %>
  <% end %>
  </div>
</div>
<br/>

<div class="row">
  <div class="col-xs-12">
    <div id="home" class="tab-pane fade in active">
      <%@group.events.each do |e| %>
        <%= render "events/event_template", e: e %>
      <% end %>
    </div>
  </div>
</div>