config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'notifications/notify'
  post 'events/set_notifs_seen'

  devise_for :users
  resources :events do
   post 'attend', on: :member
  end

  resources :groups do
    post 'subscribe', on: :member
  end

  get 'peoples' => 'peoples#index'

end

app/views/shared/_navbar.html.erb
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">GoChron</a>
          </div>
          <div class="navbar-collapse collapse" id="searchbar">
            <ul class="nav navbar-nav navbar-left">
              <li>
                <%= link_to('Events', events_path) %>
              </li>
              <li>
                <%= link_to('Groups', groups_path) %>
              </li>
              <li>
                <%= link_to('People', peoples_path) %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <%= render "shared/notification" %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog"></span> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Profile", edit_user_registration_path %>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                  </li>
                </ul>
              </li>
            </ul>
	   <%= form_tag(events_path(params[:search]), method: "get",class: "navbar-form", id: "search-form") do %>	
              <div class="form-group" style="display:inline;">
                <div class="input-group" style="display:table;">
                  <span class="input-group-addon" style="width:1%;padding-bottom: 5px;"><button type="submit"><span class="glyphicon glyphicon-search"></span></button></span>
                  <input class="form-control" name="search" placeholder="Search Events" autocomplete="off" autofocus="autofocus" type="text">
            </div>
              </div>
        <%end%>  
	</div>
          <!--/.nav-collapse -->
        </div>
      </div>

app/views/shared/_notification.html.erb
<a id="dLabel" role="button" href="/page.html" data-target="#" data-toggle="dropdown" onclick="makeNull();">
  <i class="glyphicon glyphicon-globe"><span class="icon_counter icon_counter_red"><i id="notification-counter"><%= @notifs.count %></i></span></i>
</a>
<ul class="dropdown-menu notifications" role="menu" aria-labelledby="dLabel">
  <div class="notification-heading">
    <h4 class="menu-title">Notifications</h4>
    <!--<h4 class="menu-title pull-right">View all<i class="glyphicon glyphicon-circle-arrow-right"></i></h4> -->
  </div>
  <li class="divider"></li>
  <div class="notifications-wrapper">
    <% @notifs.each do |n| %>
      <a class="content" href="#">
        <div class="notification-item">
          <h4 class="item-title">
            <%= link_to 'Click here to check event details', event_path(n.event_id) %>
            <%= simple_format "#{n.title} was updated" %>
          </h4>
        </div>
      </a>
    <% end %>
  </div>
</ul>
<script>
  function makeNull() {
    document.getElementById("notification-counter").innerHTML = 0;

    $.ajax({
       url: "/events/set_notifs_seen",
       data: {},
       type: 'POST'

    }).done(function(data) {
      if(data == 'true') {
        console.log('Successfully set all notifs to seen!');
        //location.reload();
      } else{
        alert('Unauthorized action!')
      }
    }).fail(function() {
         alert('Server Error Occurred');
    });
  }
</script>