config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'notifications/notify'
  post 'events/set_notifs_seen'

  devise_for :users
  resources :events do
   post 'attend', on: :member
  end

  resources :groups do
    post 'subscribe', on: :member
  end

  get 'peoples' => 'peoples#index'

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Sadstory
  include Mongoid::Paperclip
	
  field :title, type: String
  field :datetime, type: DateTime
  field :description, type: String
  field :location, type: String
  field :link, type: String

  belongs_to :user
  belongs_to :group
  has_and_belongs_to_many :attendees, class_name: "User", inverse_of: :attending_events

  validates :title,:datetime,presence: true
  has_mongoid_attached_file :image_attachment
  validates_attachment_file_name :image_attachment, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]

  scope :upcoming, ->() { where(:datetime.gte => Date.today).order_by(datetime: 'asc') }

  scope :this_month, ->(d) {
    where(:datetime.gte => d.beginning_of_month.beginning_of_day, :datetime.lte => d.end_of_month.end_of_day)
        .order_by(datetime: 'asc')
  }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   before_action :authenticate_user!

   def index
    request_type = (params[:request_type].blank? || params[:request_type].length == 0) ? "AllEvents" : params[:request_type]

    if params[:search]
	    search = params[:search]
      @events = Event.any_of({ :title => /.*#{search}.*/i })

    elsif request_type == 'AllEvents'
	    @events = Event.all

    elsif request_type == 'Subscribed'
      @events = current_user.subscribed_events

   elsif request_type == 'Attending'
      @events = current_user.attending_events

    elsif request_type == 'MyCreated'
      @events = current_user.events

    end
   end

   def new
     @event = Event.new
   end
   
   def edit
     @event = Event.find(params[:id]) 
   end
  
   def show
     @event = Event.find(params[:id])	
   end

   def create
     @event = Event.new(params[:event].permit(:title,:access_type,:description,:location,:datetime,:link,:image_attachment))
     @event.user_id = current_user.id
     # @event.attendee_ids << current_user.id	
     @event.group_id = params[:event][:group_id] if params[:event][:group_id]

     if @event.save
     #! Notify users about new events in subscribed groups 
      if @event.group_id.present? 
         @event.group.subscriber_ids.each do |n|
           @notify = Notification.create({user_id: n, event_id: @event.id.to_s, title: @event.title, seen: false})
         end  
      end   
       redirect_to @event
     else
       render 'new' 
     end
   end

  def update
    @event = Event.find(params[:id])

    if request.xhr?
      if (@event.user_id.to_s == params[:user_id].to_s) && (@event.update(params[:event].permit(:title,:description,:location,:datetime,:link)))
        render text: "true" and return
      else
        render text: "false" and return
      end
    end

    #!Facebook like notification when an event is updated for all its attendees
    @prev_event = @event.title
    if @event.update((params[:event].permit(:event_id,:title,:access_type,:description,:location,:datetime,:link)))
      @event.attendee_ids.each do |n|
        @notify = Notification.create({user_id: n, event_id: @event.id.to_s, title: @prev_event, seen: false})
      end
      redirect_to @event
    else
      render 'edit'
    end
  end

  # Join or remove attend status of user for an event
  # User can add an event of any group. Subscription to that group is not necessary.
  def attend
    @event = Event.find(params[:id])

    if params[:perform] == 'Join'
      current_user.attending_events << @event
      @event.attendees << current_user

      #!Send Email an hour before the event starts for all its attendees
      user_id = current_user.id.to_s
      event_id = @event.id.to_s
      t = Time.zone.parse((@event.datetime).to_s)
      #AlertsWorker.perform_in((t - Time.now - 1.hour).hour, user_id, event_id)
      #AttendeeMailer.delay_for(2.minutes.from_now).notify_attendee(current_user,@event)
      #AttendeeMailer.notify_attendee(current_user, @event).deliver_now

    elsif params[:perform] == 'Remove'
      current_user.attending_event_ids.delete(@event.id)
      @event.attendee_ids.delete(current_user.id)
    end

    current_user.save!
    @event.save!

    redirect_to request.referrer
  end

  def set_notifs_seen
    if request.xhr?
      if current_user
        Notification.where(user_id: current_user.id, seen: false).update_all(seen: true)
        render text: "true" and return
      end
    end

    render text: "false"
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
 
    redirect_to request.referrer
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_template.html.erb
<div class="panel panel-default event-template">
  <div class="media">
    <div class="media-left" style="float:left;padding:2px;">
      <a href="#">
      <% if !e.image_attachment.blank? %>
          <img class="media-object" data-src="holder.js/64x64" alt="64x64" src=<%= e.image_attachment.url %> data-holder-rendered="true" style="width: 64px; height: 64px;">
       <% else %>
         <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAANlBMVEXw8PB3xdT28vKQzdluwtLa5+qVz9rV5un48/KKy9je6etqwdJxw9PE3+VlwNHs7u+j092ByNYCtvEHAAAB90lEQVR4nO3dQXLiQBBEUYwQRgLPMPe/rNdekR1RLdcQ7x+glU/BDtw+nSRJkiRJ0pv2d03a/+NV659L0HaeTJq4ar18BC1HCwtXERLOiZBw1ll1ERLOOqsuQsJZZ9VFSDjrrLoICWedVRch4ayz6iIknHVWXYSEs86qi5Bw1ll1ERLOOqsuwiHhPTjqsdzOR3bbE+EjE+7bEvTvemxLtOqZfbKid3p9JJ+aui5r9KGJgNlbuB4L/Lh81o0nJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJPzR7Xhh3TfY0f0M+5JccRB+158cdf86/NaI9fN1XxExO+oerar8xdDt9Unn4486+jdRPY9qOouQsP8sQsL+swgJ+88iJOw/i5Cw/yxCwv6zCAn7zyIk7D+LkLD/LELC/rMICfvPIiTsP4uQsP8sQsL+swgJ+88iJOw/i5Cw/yxCwv6zCAn7zyIk7D+LkLD/LELC/rMICfvP+gXh2/89/rYHlziEFyFER0XXM1QKw8ssgvsg1sIrNkqF0VtILiSpvCblF4TB8yqvuiEkHI6QcDhCwuEICYcjJByOkHA4QsLhCAmHIyQcjpBwOELC4QgJhyMkHK6r8F72wFAY/huM1z0y4b4tVW1rInyWPW95RsLTua6jn5c9UJIkSZKkN+wblpV8EmHfJtQAAAAASUVORK5CYII=" data-holder-rendered="true" style="width: 64px; height: 64px;">
       <%end%>
    </a>
    </div>
    <div class="media-body" style="padding:2px;">
      <div class="media-heading">
        <div style="float:left;">
          <span style="font-weight:bold;font-size:15px;padding-right:15px;">
            <%= link_to e.title,event_path(e) %>
          </span>
        </div>
        <div style="float:right">
          <% if e.attendee_ids.include? current_user.id %>
           <%= link_to '', attend_event_path(e, perform: 'Remove', request_type: params[:request_type], current_cal: params[:current_cal]), method: :post,class: "btn btn-default btn-xs glyphicon glyphicon-ok added-to-cal", title: "Click if you have changed plans, and don't want to attend this event."  %>
          <% else %>
            <%= link_to '', attend_event_path(e, perform: 'Join', request_type: params[:request_type], current_cal: params[:current_cal]), method: :post,class: "btn btn-default btn-xs glyphicon glyphicon-plane", title: "Click if you want to attend this event. Can be viewed in the 'Attending' tab of calendar home page."  %>
          <% end %>

          <% if e.user_id == current_user.id %>
            <%= link_to '',edit_event_path(e),class: "btn btn-default btn-xs glyphicon glyphicon-pencil", title: "Edit"%>
            <%= link_to '',event_path(e),method: :delete, data: {confirm: 'Are you sure?'},class: "btn btn-default btn-xs glyphicon glyphicon-trash", title: "Delete" %>
          <% end %>
        </div>
      </div>

      <div style="clear:both; padding: 4px 0 4px 0;font-size: 11px;">
        <% if !e.location.blank? %>
          <span class="glyphicon glyphicon-map-marker" style="padding-right:15px;">
            <span style="font-family: Helvetica Neue, Helvetica, Arial, sans-serif;"><%= e.location %></span>
          </span>
        <% end %>

        <span class="glyphicon glyphicon-time" style="padding-right:15px;">
          <span style="font-family: Helvetica Neue, Helvetica, Arial, sans-serif;"><%= e.datetime.strftime("%b %dth %Y %I:%M%P") %></span>
        </span>

        <% if !e.group.blank? %>
          <span class="glyphicon glyphicon-certificate" style="padding-right:15px;">
            <span style="font-family: Helvetica Neue, Helvetica, Arial, sans-serif;text-decoration: underline;"><%= link_to(e.group.name, group_path(e.group)) %></span>
          </span>
        <% end %>

        <% if e.attendee_ids.count > 0 %>
          <span class="glyphicon glyphicon-plane">
            <span style="font-family: Helvetica Neue, Helvetica, Arial, sans-serif;"><%= pluralize(e.attendee_ids.count, 'person') %> attending</span>
          </span>
        <% end %>
      </div>

      <div>
        <%= truncate(e.description || "", length: 80) { link_to "more", event_path(e) } %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="row navbar-clearance">
  <%= form_for @event do |f| %>
    <%if @event.nil? %>
      <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@event.errors.count, "error") %> prohibited this article from being saved:
          </h2>
          <ul>
            <% @event.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <%else%>
        <% if @event.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@event.errors.count, "error") %> prohibited this article from being saved:
     		    </h2>
            <ul>
              <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
    <%end%>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><%= "Create Event" %></h4>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br />
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :location %>
          <%= f.text_field :location, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :datetime %><br/>
          <%= f.datetime_select :datetime %>
        </div>
        <div class="form-group">
          <%= f.label :link %>
          <%= f.text_field :link, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image_attachment %>
          <%= f.file_field :image_attachment, class: "form-control" %>
        </div>
        <% if params[:group_id] != nil %>
          <%= f.hidden_field :group_id,value: params[:group_id] %>
        <% end %>
        <%= f.submit :default => "Submit", class: "btn btn-primary btn-sm" %>
        <%= link_to 'Back',events_path, class: "btn btn-primary btn-sm" %>
      </div> <!-- panel-body -->
    </div> <!-- panel -->
  <% end %>
</div>

app/views/events/index.html.erb
<div class="row navbar-clearance">
  <div class="col-xs-9">
    <div class="btn-group" role="group" aria-label="FilterButtons">
      <%= link_to 'All Events',events_path(:request_type => 'AllEvents'), class: "btn btn-default btn-sm filterbtn", id: 'AllEvents' %>
      <%= link_to 'Subscribed',events_path(:request_type => 'Subscribed'), class: "btn btn-default btn-sm filterbtn", id: 'Subscribed' %>
      <%= link_to 'Attending',events_path(:request_type => 'Attending'), class: "btn btn-default btn-sm filterbtn", id: 'Attending' %>
      <%= link_to 'My Created',events_path(:request_type => 'MyCreated'), class: "btn btn-default btn-sm filterbtn", id: 'MyCreated' %>
    </div>
  </div>
</div>
<hr/>

<div class="row">
  <div class="col-xs-9">
    <%= link_to 'Create Event',new_event_path, class: "btn btn-default btn-sm" %>
  </div>
</div>
<br/>

<div class="row">
  <div class="col-xs-12">
    <div id="home" class="tab-pane fade in active">
      <% @events.each do |e| %>
        <%= render "event_template", e: e %>
      <% end %>
    </div>
  </div>
</div>

<script>
  var request_type = '<%= params[:request_type] %>';

  // Select active tab
  if(request_type.length > 0) {
    $('.filterbtn').removeClass('active')
    $('#'+request_type).addClass('active')
  } else {
    $('#AllEvents').addClass('active')
  }

</script>

app/views/events/show.html.erb
<div class="row navbar-clearance">
  <div class="panel panel-default webform">
    <div class="panel-heading">
      <h4><%= "Event Details" %></h4>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <h6><b><%= "Event Name:" %></b></h6>
        <%= @event.title %>
      </div>
      <div class="form-group">
        <h6><b><%= "Description:" %></b></h6>
        <%= @event.description %>
      </div>
      <div class="form-group">
        <h6><b><%= "Location:" %></b></h6>
        <%= @event.location %>
        <a href="https://maps.google.com?q=<%=@event.location%>" target="_blank"><img src="<%= asset_path('gmaps.png') %>" title="Locate on Google Maps" height="36" width="36"></a>
      </div>
      <div class="form-group">
        <h6><b><%= "Date/Time:" %></b></h6>
        <%= @event.datetime %>
      </div>
      <div class="form-group">
        <h6><b><%= "Event link:" %></b></h6>
        <%= @event.link %>
      </div>
      <div class="form-group">
        <h6><b><%= "Event Image:" %></b></h6>
        <%= image_tag @event.image_attachment.url %>
      </div>
      <div class="form-group">
        <h6><b><%= "Share/Add:" %></b></h6>
        <a href="https://www.google.com/calendar/render?action=TEMPLATE&text=<%=@event.title%>&details=<%=@event.description%>&location=<%=@event.location%>&sf=true&output=xml" target="_blank"><img src="<%= asset_path('gcal.png') %>" title="Add Event to Google Calendar" height="36" width="36"></a>
        <a href="https://www.facebook.com/dialog/share?app_id=145634995501895&display=popup&href=www.ufl.edu&redirect_uri=https%3A%2F%2Ffacebook.com" target="_blank"><img src="<%=asset_path('fbshare.png')%>" width="30" height="30" title="Share on Facebook"></a>
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= event_path(@event) %>" data-text="<%= @event.title%> <%=@event.datetime%> Or access at <%= event_path(@event) %>" data-count="none">Tweet</a>
        <a href="https://plus.google.com/share?url={<%=event_path(@event)%>}" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><img src="https://www.gstatic.com/images/icons/gplus-32.png" alt="Share on Google+" title="Share on Google+"/></a>
       </div>
    </div> <!--panel-body-->
  </div> <!--panel-->
</div> <!--row-->

<div id="fb-root"></div>
<script>
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
// FB.ui({
//   method: 'share',
//   href: '<%=event_path(@event)%>',
//   }, function(response){});
</script>